ALTER TABLE companies
ADD COLUMN IF NOT EXISTS short_name VARCHAR(50),

ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) DEFAULT '#1565C0',

ADD COLUMN IF NOT EXISTS secondary_color VARCHAR(20) DEFAULT '#0D47A1',

ADD COLUMN IF NOT EXISTS signature_url TEXT,

ADD COLUMN IF NOT EXISTS qr_base_url TEXT;
